from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 509)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Label_name_of_app = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Label_name_of_app.setFont(font)
        self.Label_name_of_app.setObjectName("Label_name_of_app")
        self.gridLayout.addWidget(self.Label_name_of_app, 0, 1, 1, 1)
        self.Picture_place = QtWidgets.QLabel(self.centralwidget)
        self.Picture_place.setMinimumSize(QtCore.QSize(600, 450))
        self.Picture_place.setMaximumSize(QtCore.QSize(600, 450))
        self.Picture_place.setFrameShape(QtWidgets.QFrame.Box)
        self.Picture_place.setText("")
        self.Picture_place.setObjectName("Picture_place")
        self.gridLayout.addWidget(self.Picture_place, 1, 1, 2, 1)
        self.Label_type_of_map = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Label_type_of_map.setFont(font)
        self.Label_type_of_map.setObjectName("Label_type_of_map")
        self.gridLayout.addWidget(self.Label_type_of_map, 0, 0, 1, 1)
        self.Type_of_map = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.Type_of_map.setFont(font)
        self.Type_of_map.setObjectName("Type_of_map")
        self.Type_of_map.addItem("")
        self.Type_of_map.addItem("")
        self.Type_of_map.addItem("")
        self.gridLayout.addWidget(self.Type_of_map, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Label_name_of_app.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Перемещайся по карте</span></p></body></html>"))
        self.Label_type_of_map.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Тип карты</p></body></html>"))
        self.Type_of_map.setItemText(0, _translate("MainWindow", "Схема"))
        self.Type_of_map.setItemText(1, _translate("MainWindow", "Спутник"))
        self.Type_of_map.setItemText(2, _translate("MainWindow", "Гибрид"))
